secrets:
  redis_addr: ${REDIS_HOST}:${REDIS_PORT}
  redis_password: ${REDIS_PASSWORD}

  proxy_port: ${PROXY_PORT}
  proxy_addr: ${HOST}:${PROXY_PORT}

  metrics_addr: ${HOST}:${METRICS_PORT}

# real-time config
proxy_settings:
  targets:
    - { team_host: 10.136.179.131, port: 1224 }
    - { team_host: 91.228.152.143, port: 5001 }
