secrets:
  redis_addr: ${REDIS_HOST}:${REDIS_PORT}
  redis_password: ${REDIS_PASSWORD}

  proxy_addr: 0.0.0.0:1337
  metrics_addr: 0.0.0.0:8989

proxy_settings:
  service_ports: [3444, 3445, 3446]

  team_ips: [10.0.12.23, 10.0.12.24, 10.0.12.25]

  targets:
      - { team_ip: 10.136.179.1, port: 4554 }
      - { team_ip: 10.0.13.23, port: 4555 }
