version: "3.2"

services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "$REDIS_PORT:6379"
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf