version: "3.2"

services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "2139:6379"
    command: redis-server --requirepass SUP3RS3CRET
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf