services:
  service:
    container_name: test-service
    build: 
      context: ./service
      dockerfile: Dockerfile
  
  redis:
    container_name: test-redis
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  beta:
    container_name: test-beta
    build: 
      context: ../.
      dockerfile: test.Dockerfile
    # for iptables
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
      - service
    volumes:
      - $PWD/config.yaml:/config.yaml
      - $PWD/.env:/.env

  checker:
    container_name: test-checker
    build: 
      context: ./checker
      dockerfile: Dockerfile
    depends_on:
      - beta
