name: beta

on:
  push:
    branches: ["release/*", "feature/*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run cargo build
        run: cargo build --verbose

  cargo-tests:
    runs-on: ubuntu-latest
    needs: cargo-build

    steps:
      - uses: actions/checkout@v4
      - name: Run cargo test
        run: cargo test --verbose

  e2e:
    runs-on: ubuntu-latest
    needs: cargo-tests

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Run e2e tests
        run: |
          cd e2e
          docker compose up --build --abort-on-container-exit
