name: Rust
run-name: ${{ github.actor }} is running

on:
  push:
    branches: ["release/*", "feature/*"]

  pull_request:
    branches: ["release/*", "feature/*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
